### ISSUE TITLE
ModuleNotFoundError: No module named 'solrSource'

### ISSUE THREAD

**Issue by scalad** [o19s/solr-to-es#19]
ModuleNotFoundError: No module named 'solrSource'
![image](https://user-images.githubusercontent.com/16514952/95694292-e8164000-0c63-11eb-8822-39f4f7d75d12.png)

**Comment by epugh** [comment]
Well..   I tested it..  and yeah...  I get your error too!  I tried banging around with the imports, but my Python-fu isn't strong, and didn't resolve it.  I also looked back at the past couple of PR's that were mergged to see if there was an obvious culprit, but no joy.  This will need someone with a bit more Python fu to fix, however happy to merge any PR's!

**Comment by atarora** [comment]
`mymacbook0050:solr-to-es aarora$ git diff
diff --git a/solr_to_es/__main__.py b/solr_to_es/__main__.py
index adb8cf0..f7d82e7 100644
--- a/solr_to_es/__main__.py
+++ b/solr_to_es/__main__.py
@@ -2,7 +2,8 @@ from __future__ import print_function
 import argparse
 from elasticsearch import Elasticsearch
 import elasticsearch.helpers
-from solrSource import SlowSolrDocs
+from solr_to_es.solrSource import SlowSolrDocs
+import pysolr`

Should fix it !

**Comment by epugh** [comment]
I'm closing this issue based on the merge of the patch that @atarora provided!  Thanks!
