### ISSUE TITLE
Support for ES 6.x+

### ISSUE THREAD

**Issue by lukas681** [o19s/solr-to-es#5]
As ES added strict content checking in ES6 (https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests) , this tool can not be applied for Elastic Search Version 6 and above.

**Comment by epugh** [comment]
Fixed...

**Comment by whisere** [comment]
@epugh this is not fixed?

**Comment by epugh** [comment]
Not sure I get your comment...    It's been a long time since I checked this...   looking, I think it is fixed...   So I'll close the issue.   thanks!
